@startuml AC_Container_Diagram
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
!define MAT https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!include DEV2/nodejs.puml
!include DEV2/html5.puml
' !include DEV2/amazonwebservices.puml
!include DEV2/javascript.puml
!include DEV2/github.puml

LAYOUT_WITH_LEGEND()

title [Container Diagram] All Contributors

Person(user, "User")

System_Boundary(ac, "All Contributors") {
  Container(website, "Website", "Docusaurus", "Documentation", "html5")
  Container(spec, "Specification", "JSON", "Contains the emoji key, synonyms and aliases", "json")
  Container(lib, "Library", "JS", "Reads/writes configuration and updates markdown text", "javascript")
  Container(cli, "CLI", "Node.js", "`all-contributors-cli`", "nodejs")
  Container(app, "App", "Node.js", "Github App-driven bot", "nodejs")
  Container(acl, "AC-Learn", "Node.js", "Multi-class label classifier", "nodejs")

  Rel(lib, spec, "reads", "CJS/ES import")
  Rel(cli, lib, "uses", "CJS/ES import")
  Rel(app, lib, "uses", "CJS/ES import")
  Rel(website, spec, "reads", "??")
  Rel(lib, acl, "uses", "CJS/ES import")
}

' System_Ext(sentry, "Sentry", "App monitoring / error tracking", "sentry")
System_Ext(uptime, "UptimeRobot", "Monitoring")
System_Ext(logflare, "Logflare", "Log aggregation", "logflare")
System_Ext(netlify, "Netlify", "", "netlify")
' System_Ext(aws, "AWS", "", "amazonwebservices")
System_Ext(vercel, "Vercel")
System_Ext(gh, "GitHub", "", "github")
Container_Ext(probot, "Probot", "GitHub Apps to automate and improve your workflow")
Container_Ext(limdu, "Limdu.js", "ML framework for Node.js")

Rel(user, app, "instructs", "GitHub comments via GitHub Events")
Rel(user, cli, "uses", "Any terminal")
Rel(user, website, "visits/reads", "Web")
Rel(website, netlify, "hosted on")
Rel_R(app, vercel, "serviced by")
Rel(logflare, vercel, "listening to", "HTTPS")
Rel(uptime, vercel, "monitors", "HTTPS")
Rel(app, probot, "depends on")
Rel(app, gh, "listens to", "webhooks")
Rel_L(acl, limdu, "uses", "CJS import")

@enduml