@startuml AC_Container_Diagram
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
!define MAT https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material
!include DEV2/nodejs.puml
!include DEV2/html5.puml
!include DEV2/javascript.puml
!include DEV2/github.puml

LAYOUT_WITH_LEGEND()

title [Container Diagram] All Contributors

Person(devs, "All Contributors team", "A core member of All Contributors.")
Person(user, "User", "A user of our software system.")

System_Ext(crowdin, "Crowdin", "Cloud-based localization management solution.")
System_Ext(gh, "GitHub", "Code Hosting and VCS", "github")
System_Ext(netlify, "Netlify", "Cloud-based hosting platform for static sites, web apps and serverless functions.")
System_Ext(vercel, "Vercel", "Cloud platform for static sites and serverless functions.")
Container_Ext(clui, "CLUI", "CL UI toolkit for Node.js.")
Container_Ext(chalk, "Chalk", "Terminal string styler.")
Container_Ext(compromise, "Compromise", "NLP package.")
Container_Ext(inquirer, "Inquirer", "Collection of common interactive CLIs.")
Container_Ext(limdu, "Limdu.js", "ML framework for Node.js")
Container_Ext(nclr, "NClr", "Coloured logs (with symbols)")
Container_Ext(nyc, "Name Your Contributors", "Package that gets all of the code reviewers, commenters, issue and PR creators from your organization or repo.")
Container_Ext(probot, "Probot", "GitHub App framework.")
Container_Ext(tvtsplit, "TVT Split", "Dataset splitter into train/validation/test sets")
Container_Ext(yargs, "Yargs", "CLI argument parser and help section generator")

System_Boundary(ac, "All Contributors") {
  Container(acl, "AC-Learn", "Node.js", "Multi-class label classifier", "nodejs")[[../acl/ACL_Component_Diagram.svg]]
  Container(app, "App", "Node.js", "GitHub app-driven bot", "nodejs") [[../app/App_Component_Diagram.svg]]
  Container(cli, "CLI", "Node.js", "all-contributors-cli", "nodejs") [[../cli/Cli_Component_Diagram.svg]]
  Container(lib, "Library", "Node.js", "Reads/writes configuration and updates markdown text", "javascript") [[../lib/Lib_Component_Diagram.svg]]
  Container(spec, "Specification", "JSON", "Contains the emoji key, synonyms and aliases", "json") [[../spec/Spec_Component_Diagram.svg]]
  Container(website, "Website", "Docusaurus", "Documentation", "html5") [[../website/Website_Component_Diagram.svg]]
}

Rel(acl, clui, "uses", "CJS import")
Rel_L(acl, limdu, "uses", "CJS import")
Rel(acl, nclr, "uses", "CJS import")
Rel(acl, spec, "reads", "CJS import")
Rel(acl, tvtsplit, "uses", "CJS import")
Rel(devs, acl, "maintain")
Rel(devs, app, "maintain")
Rel(devs, cli, "maintain")
Rel(devs, lib, "maintain")
Rel(devs, spec, "maintain")
Rel(devs, vercel, "monitor")
Rel(devs, website, "maintain")
Rel(app, compromise, "uses", "CJS import")
Rel(app, gh, "listens to", "webhooks")
Rel(app, lib, "uses", "CJS import")
Rel(app, probot, "implements", "CJS import")
Rel_L(app, vercel, "serviced by", "??")
Rel(cli, clui, "uses", "CJS import")
Rel(cli, chalk, "depends on", "CJS import")
Rel(cli, inquirer, "uses", "CJS import")
Rel(cli, lib, "uses", "CJS import")
Rel(cli, nyc, "uses", "CJS import")
Rel(cli, yargs, "depends on", "CJS import")
Rel(lib, acl, "uses", "CJS import")
Rel(lib, spec, "reads", "CJS import")
Rel(user, app, "instructs", "GitHub comments via GitHub Events")
Rel(user, cli, "uses", "Any terminal")
Rel(user, website, "visits/reads", "Web")
Rel_L(website, crowdin, "gets translations from", "Java/Yarn")
Rel_L(website, netlify, "hosted on", "??")
Rel(website, spec, "reads", "??")

@enduml