@startuml(id=ac-containers)
title All Contributors - Containers
caption Container view for AC

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<2>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<18>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<19>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<20>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<21>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
rectangle "==All Contributors team\n<size:10>[Person]</size>\n\nMaintain the system" <<2>> as 2
rectangle "==User\n<size:10>[Person]</size>\n\nuses the system" <<1>> as 1
package "All Contributors\n[Software System]" {
  rectangle "==App\n<size:10>[Container: Node.js]</size>\n\nGitHub app-driven bot" <<20>> as 20
  rectangle "==CLI\n<size:10>[Container: Node.js]</size>\n\n`all-contributors`" <<18>> as 18
  rectangle "==Core\n<size:10>[Container: Node.js]</size>\n\nReads/writes configuration, updates markdown text and contains spec and DL model" <<21>> as 21
  rectangle "==Website\n<size:10>[Container: Docusaurus]</size>\n\nDocumentation" <<19>> as 19
}
20 .[#707070].> 21 : "imports methods from\n<size:8>[CJS import]</size>"
18 .[#707070].> 21 : "imports methods from\n<size:8>[CJS import]</size>"
19 .[#707070].> 21 : "gets specification from\n<size:8>[CJS import]</size>"
@enduml