@startuml AC_System_Context
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
' !include DEV2/amazonwebservices.pumlpuml
!include DEV2/github.puml

LAYOUT_WITH_LEGEND()

title [System Context Diagram] All Contributors

Person(user, "User")

System(ac, "All Contributors", "System for recognizing contributors to an open source project in a way that rewards each and every contribution")
System_Ext(uptime, "UptimeRobot", "Monitoring")
System_Ext(logflare, "Logflare", "Log aggregation", "logflare")
System_Ext(netlify, "Netlify", "", "netlify")
System_Ext(vercel, "Vercel")
System_Ext(gh, "GitHub", "", "github")

Rel(user, ac, "interacts with")
Rel(ac, netlify, "hosted on")
Rel(ac, vercel, "serviced by")
Rel(logflare, vercel, "listening to", "HTTPS")
Rel(uptime, vercel, "monitors", "HTTPS")
Rel(ac, gh, "listens to", "webhooks")

@enduml