@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
!include DEV2/nodejs.puml
!include DEV2/javascript.puml

LAYOUT_WITH_LEGEND()

title [Component Diagram] Library container

Container_Boundary(lib, "Library") {
  Component(cfg, "Configuration Manager", "Node.js", "Read/writes the configuration", "nodejs")
  Component(md, "Markdown Manager", "Node.js", "Read/writes Markdown files with the resulting table", "nodejs")

  Rel_Back_Neighbor(cfg, md, "uses")
}

@enduml