@startuml Cli_Component_Diagram
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
!include DEV2/nodejs.puml
!include DEV2/html5.puml
!include DEV2/javascript.puml

LAYOUT_WITH_LEGEND()

title [Component Diagram] CLI container (Idea 1)

' TODO Rework this ball of mud

Container(website, "Website", "Docusaurus", "Documentation", "html5") [[../website/Website_Component_Diagram.svg]]
Container(core, "Core", "Node.js", "Reads/writes configuration, updates markdown text and contains spec and DL model", "nodejs") [[../core/Core_Component_Diagram.svg]]
Container(app, "App", "Node.js", "Github App-driven bot", "nodejs") [[../app/App_Component_Diagram.svg]]

Container_Boundary(cli, "CLI") {
  ' Component(api, "API", "Node.js", "", "nodejs")
  Component(interface, "CL Interface", "Node.js", "", "nodejs")
  Component(contributors, "Contributors", "Node.js", "", "nodejs")
  Component(discover, "Discover", "Node.js", "", "nodejs")
  Component(generate, "Generator", "Node.js", "", "nodejs")
  Component(init, "Init", "Node.js", "Initialise the config", "nodejs")
  Component(repo, "Repo", "Node.js", "", "nodejs")
  Component(util, "Utils", "Node.js", "", "nodejs")

  ' Rel(api, generate, "exposes", "CJS")
  ' Rel(api, init, "exposes addContributorsList() and addBadge()", "CJS")
  ' Rel(api, contributors, "exposes addWithDetails()", "CJS")
  Rel(interface, init, "calls", "`init` command")
  Rel(interface, generate, "calls", "`generate` command")
  Rel(interface, util, "depends on", "CJS import")
  Rel(interface, repo, "depends on", "CJS import")
  Rel(interface, contributors, "calls", "`add` command")
  Rel(interface, discover, "calls", "`fetch` command")
  Rel(contributors, util, "depends on", "CJS import")
  Rel(contributors, repo, "depends on", "CJS import")
  Rel(init, util, "depends on", "CJS import")
}

Component_Ext(yargs, "Yargs", "Node.js", "CLI argument parser and help section generator", "nodejs")
Component_Ext(chalk, "Chalk", "Node.js", "Terminal string styler", "nodejs")
Component_Ext(inquirer, "Inquirer", "Node.js", "Collection of common interactive CLI", "nodejs")
Component_Ext(clui, "CLUI", "Node.js", "Collection of common interactive CLI", "nodejs")

Rel(app, core, "uses", "CJS/ES import")
Rel(website, core, "uses", "??")
Rel(discover, core, "uses", "CJS import")
Rel(generate, core, "uses", "CJS import")
Rel(init, core, "uses", "CJS import")
Rel(util, core, "uses", "CJS import")

Rel(interface, yargs, "depends on", "CJS import")
Rel(interface, chalk, "depends on", "CJS import")
Rel(interface, inquirer, "depends on", "CJS import")
Rel(contributors, inquirer, "depends on", "CJS import")
Rel(discover, clui, "depends on", "CJS import")
Rel(init, inquirer, "depends on", "CJS import")

Person(user, "User")
Rel(user, interface, "uses", "Any terminal")
Rel(user, app, "instructs", "GitHub comments via GitHub Events")
Rel(user, website, "visits/reads", "Web")

@enduml