@startuml Core_Component_Diagram
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
!define DEV2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/dev2
!include DEV2/nodejs.puml
!include DEV2/html5.puml
!include DEV2/javascript.puml
!include DEV2/github.puml

LAYOUT_WITH_LEGEND()

title [Component Diagram] Core container (Idea 1)

Container(website, "Website", "Docusaurus", "Documentation", "html5")
Container(cli, "CLI", "Node.js", "`all-contributors-cli`", "nodejs")
Container(app, "App", "Node.js", "Github App-driven bot", "nodejs")

Container_Boundary(core, "Core") {
  Component(spec, "Specification", "JSON", "Contains the emoji key, synonyms and aliases", "json")
  Component(lib, "Library", "JS", "Reads/writes configuration and updates markdown text", "javascript")
  Component(acl, "AC-Learn", "Node.js", "Multi-class label classifier", "nodejs")

  Rel(lib, spec, "reads", "CJS/ES import")
  Rel(lib, acl, "uses", "CJS/ES import")
}

Container_Ext(limdu, "Limdu.js", "Node.js", "ML framework for Node.js", "nodejs")
Container_Ext(nyc, "Name Your Contributors", "Node.js", "Package that gets all of the code reviewers, commenters, issue and PR creators from your organization or repo.", "nodejs")

Rel(cli, lib, "uses", "CJS/ES import")
Rel(app, lib, "uses", "CJS/ES import")
Rel(website, lib, "uses", "??")
Rel(acl, limdu, "uses", "CJS import")
Rel(lib, nyc, "uses", "CJS import")

@enduml