@startuml(id=CLI_components)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - CLI - Components

System_Ext(clui, "CLUI", "CL UI toolkit for Node.js.")
System_Ext(chalk, "Chalk", "Terminal string styler.")
System_Ext(inquirer, "Inquirer", "Collection of common interactive CLIs.")
Container(lib, "Library", "Node.js", "Reads/writes configuration and updates markdown text")
System_Ext(yargs, "Yargs", "CLI argument parser and help section generator")
Container_Boundary(cli_boundary, CLI) {
  Component(clinterface, "CL Interface", "Node.js", "Command Line Interface executable")
  Component(contributors, "Contributors", "Node.js", "Add/update contributors")
  Component(discover, "Discover", "Node.js", "Contributor discovery")
  Component(generator, "Generator", "Node.js", "Table generation")
  Component(init, "Init", "Node.js", "Initialise the config")
  Component(repo, "Repo", "Node.js", "GitHub/GitLab adapters")
  Component(utils, "Utils", "Node.js", "Utilities")
}
Rel_D(clinterface, chalk, "depends on", "CJS import")
Rel_D(clinterface, contributors, "calls", "`add` command")
Rel_D(clinterface, discover, "calls", "`fetch` command")
Rel_D(clinterface, generator, "calls", "`generate` command")
Rel_D(clinterface, init, "calls", "`init` command")
Rel_D(clinterface, repo, "depends on", "CJS import")
Rel_D(clinterface, utils, "depends on", "CJS import")
Rel_D(clinterface, yargs, "depends on", "CJS import")
Rel_D(contributors, inquirer, "uses", "CJS import")
Rel_D(discover, clui, "uses", "CJS import")
Rel_D(discover, lib, "uses", "CJS import")
Rel_D(generator, lib, "uses", "CJS import")
Rel_D(init, inquirer, "uses", "CJS import")
Rel_D(init, lib, "uses", "CJS import")
Rel_D(utils, lib, "uses", "CJS import")
@enduml