@startuml(id=AC_Containers)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - Containers

Person(2, "All Contributors team", "A core member of All Contributors.")
System(36, "CLUI", "CL UI toolkit for Node.js.")
System(33, "Chalk", "Terminal string styler.")
System(32, "Compromise", "NLP package.")
System(30, "Crowdin", "Cloud-based localization management solution.")
System(27, "GitHub", "Code Hosting and VCS")
System(35, "Inquirer", "Collection of common interactive CLIs.")
System(37, "Limdu.js", "ML framework for Node.js")
System(39, "NClr", "Coloured logs (with symbols)")
System(40, "Name Your Contributors", "Package that gets all of the code reviewers, commenters, issue and PR creators from your organization or repo.")
System(26, "Netlify", "Cloud-based hosting platform for static sites, web apps and serverless functions.")
System(31, "Probot", "GitHub App framework.")
System(38, "TVT Split", "Dataset splitter into train/validation/test sets")
Person(1, "User", "A user of our software system.")
System(25, "Vercel", "Cloud platform for static sites and serverless functions.")
System(34, "Yargs", "CLI argument parser and help section generator")
System_Boundary(3_boundary, All Contributors) {
  Container(20, "AC-Learn", "Node.js", "Multi-class label classifier")
  Container(15, "App", "Node.js", "GitHub app-driven bot")
  Container(4, "CLI", "Node.js", "all-contributors-cli")
  Container(18, "Library", "Node.js", "Reads/writes configuration and updates markdown text")
  Container(19, "Specification", "JSON", "Contains the emoji key, synonyms and aliases")
  Container(12, "Website", "Docusaurus", "Documentation")
}
Rel_D(20, 36, "uses", "CJS import")
Rel_D(20, 37, "uses", "CJS import")
Rel_D(20, 39, "uses", "CJS import")
Rel_D(20, 19, "reads", "CJS import")
Rel_D(20, 38, "uses", "CJS import")
Rel_D(2, 20, "maintain")
Rel_D(2, 15, "maintain")
Rel_D(2, 4, "maintain")
Rel_D(2, 18, "maintain")
Rel_D(2, 19, "maintain")
Rel_D(2, 25, "monitor")
Rel_D(2, 12, "maintain")
Rel_D(15, 32, "uses", "CJS import")
Rel_D(15, 27, "listens to", "webhooks")
Rel_D(15, 18, "uses", "CJS import")
Rel_D(15, 31, "implements", "CJS import")
Rel_D(15, 25, "serviced by", "??")
Rel_D(4, 36, "uses", "CJS import")
Rel_D(4, 33, "depends on", "CJS import")
Rel_D(4, 35, "uses", "CJS import")
Rel_D(4, 18, "uses", "CJS import")
Rel_D(4, 40, "uses", "CJS import")
Rel_D(4, 34, "depends on", "CJS import")
Rel_D(18, 20, "uses", "CJS import")
Rel_D(18, 19, "reads", "CJS import")
Rel_D(1, 15, "instructs", "GitHub comments via GitHub Events")
Rel_D(1, 4, "uses", "Any terminal")
Rel_D(1, 12, "visits/reads", "Web")
Rel_D(12, 30, "gets translations from", "Java/Yarn")
Rel_D(12, 26, "hosted on", "??")
Rel_D(12, 19, "reads", "??")
@enduml