@startuml(id=SystemLandscape)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title System Landscape

Person(2, "All Contributors team", "A core member of All Contributors.")
Person(1, "User", "A user of our software system.")
System(3, "All Contributors", "System for recognizing contributors to an open source project in a way that rewards each and every contribution.")
System(40, "CLUI", "CL UI toolkit for Node.js.")
System(37, "Chalk", "Terminal string styler.")
System(36, "Compromise", "NLP package.")
System(34, "Crowdin", "Cloud-based localization management solution.")
System(31, "GitHub", "Code Hosting and VCS")
System(39, "Inquirer", "Collection of common interactive CLIs.")
System(41, "Limdu.js", "ML framework for Node.js")
System(33, "Logflare", "Log aggregation.")
System(43, "NClr", "Coloured logs (with symbols)")
System(44, "Name Your Contributors", "Package that gets all of the code reviewers, commenters, issue and PR creators from your organization or repo.")
System(30, "Netlify", "Cloud-based hosting platform for static sites, web apps and serverless functions.")
System(35, "Probot", "GitHub App framework.")
System(42, "TVT Split", "Dataset splitter into train/validation/test sets")
System(32, "UptimeRobot", "Monitoring.")
System(29, "Vercel", "Cloud platform for static sites and serverless functions.")
System(38, "Yargs", "CLI argument parser and help section generator")
Rel_D(2, 3, "maintain", "")
Rel_D(2, 29, "monitor", "")
Rel_D(3, 40, "uses", "CJS import")
Rel_D(3, 37, "depends on", "CJS import")
Rel_D(3, 36, "uses", "CJS import")
Rel_D(3, 34, "gets translations from", "Java/Yarn")
Rel_D(3, 31, "listens to", "webhooks")
Rel_D(3, 39, "uses", "CJS import")
Rel_D(3, 41, "uses", "CJS import")
Rel_D(3, 43, "uses", "CJS import")
Rel_D(3, 44, "uses", "CJS import")
Rel_D(3, 30, "hosted on", "??")
Rel_D(3, 35, "implements", "CJS import")
Rel_D(3, 42, "uses", "CJS import")
Rel_D(3, 29, "serviced by", "??")
Rel_D(3, 38, "depends on", "CJS import")
Rel_D(33, 29, "listens to", "HTTPS")
Rel_D(32, 29, "monitors", "HTTPS")
Rel_D(1, 3, "interacts with", "")
@enduml