@startuml(id=AC-Learn_components)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - AC-Learn - Components

System_Ext(clui, "CLUI", "CL UI toolkit for Node.js.")
Container(lib, "Library", "Node.js", "Reads/writes configuration and updates markdown text")
System_Ext(limdu, "Limdu.js", "ML framework for Node.js")
System_Ext(nclr, "NClr", "Coloured logs (with symbols)")
Container(spec, "Specification", "JSON", "Contains the emoji key, synonyms and aliases")
System_Ext(tvtsplit, "TVT Split", "Dataset splitter into train/validation/test sets")
Container_Boundary(acl_boundary, AC-Learn) {
  Component(classifier, "Classifier", "Node.js", "Classification builder")
  Component(cm, "Confusion Matrix", "Node.js", "Multi-class focused confusion matrix builder")
  Component(labels, "Labels", "Node.js/JSON", "Label dataset aggregation")
  Component(learner, "Learner", "Node.js", "DL model wrapper")
}
Rel_D(learner, clui, "uses", "CJS import")
Rel_D(learner, classifier, "uses", "CJS import")
Rel_D(learner, cm, "uses", "CJS import")
Rel_D(learner, labels, "uses", "CJS import")
Rel_D(learner, limdu, "uses", "CJS import")
Rel_D(learner, nclr, "uses", "CJS import")
Rel_D(learner, spec, "reads", "CJS import")
Rel_D(learner, tvtsplit, "uses", "CJS import")
Rel_D(lib, learner, "uses", "CJS import")
Rel_D(lib, spec, "reads", "CJS import")
@enduml