@startuml(id=Website_components)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - Website - Components

System_Ext(crowdin, "Crowdin", "Cloud-based localization management solution.")
System_Ext(netlify, "Netlify", "Cloud-based hosting platform for static sites, web apps and serverless functions.")
Container(spec, "Specification", "JSON", "Contains the emoji key, synonyms and aliases")
Container_Boundary(website_boundary, Website) {
  Component(docs, "Docs", "Markdown", "Specification/CLI/Bot documentation")
  Component(site, "Website", "Docusaurus", "Documentation")
}
Rel_D(site, crowdin, "gets translations from", "Java/Yarn")
Rel_D(site, docs, "integrates")
Rel_D(site, netlify, "hosted on", "??")
Rel_D(site, spec, "reads", "??")
@enduml