@startuml(id=App_components)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - App - Components

System_Ext(compromise, "Compromise", "NLP package.")
System_Ext(gh, "GitHub", "Code Hosting and VCS")
Container(lib, "Library", "Node.js", "Reads/writes configuration and updates markdown text")
System_Ext(probot, "Probot", "GitHub App framework.")
Container_Boundary(app_boundary, App) {
  Component(api, "API", "Node.js", "Source code and GH Webhooks")
  Component(applib, "Lib", "Node.js", "Library code for the bot")
}
Rel_D(api, gh, "listens to", "webhooks")
Rel_D(api, applib, "uses", "CJS import")
Rel_D(applib, compromise, "uses", "CJS import")
Rel_D(applib, lib, "uses", "CJS import")
Rel_D(applib, probot, "implements", "CJS import")
@enduml