@startuml(id=ac-context)
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title All Contributors - System Context
caption The system context view for AC

Person(2, "All Contributors team", "Maintain the system")
Person(1, "User", "uses the system")
package "Enterprise" {
  System(3, "All Contributors", "System for recognizing contributors to an open source project in a way that rewards each and every contribution")
}
Rel_D(2, 3, "maintain")
Rel_D(1, 3, "interacts with")
@enduml